# Generated by Django 5.1.1 on 2025-01-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=40)),
                ('esal', models.FloatField(default=None)),
            ],
        ),
    ]
